### ISSUE TITLE
Create basic framework to access Lex Machina API

### ISSUE THREAD

**Issue by daveslusher-lm** [LexMachinaInc/python-lexmachina-api-client#1]
Analogously to how https://github.com/LexMachinaInc/node-lexmachina-api-client works, we need a python library that will provide some of the low-level details of accessing the API. It does not need to be identical to the node version. The python version should do things in the python way, whatever those might be.

These basically correspond to:

- [x] Create helper to get authentication tokens
- [x] Store the tokens persistently in a way that can be checked for expiry
- [x] Transparently add this header to every call based on the above
- [x] Create one function to pull down a /list endpoint data
- [x] Create one function to get an entity endpoint like /attorneys
- [x] Create one function to get a /search endpoint

**Comment by mel-seto** [comment]
Woah it's a completely different code base so no labels available

**Comment by rmblau** [comment]
Unit tests still need writing, will need assistance from @mel-seto.

**Comment by mel-seto** [comment]
@rmblau you may want to check off the tasks already completed in the original issue description, and mark this issue as done if it is.
